### PR TITLE
Folder structure

### PR DESCRIPTION
**Pull request by Lil-Adonis**
removed inactive codes and updated All-Livestock folder

### CODE REVIEW

**Comment by kessysenlong** [comment]
@Lil-Adonis let's maintain a reasonable camel case naming convention for our files and have files grouped based on the module or feature i.e we should name files as <feature><element-type>

Something like "addForm" instead of "Add",  "livestockTable" or "livestockDashboard" instead of "Livestock", "recordSaleModal" instead of "RecordSale"

image

**Comment by kessysenlong** [comment]
We DO NOT have a "users table" so that should be renamed globally

**Comment by kessysenlong** [comment]
What is the difference between the livestock folder and the All-livestock folder?

**Comment by kessysenlong** [comment]
All files should be named in camel case. 

And which folder should these files fall under? 
image

**Comment by Lil-Adonis** [comment]
> We DO NOT have a "users table" so that should be renamed globally

i understand it should be more like livestockTable but that has been used so maybe i will think of more suitble name for its usage.


> What is the difference between the livestock folder and the All-livestock folder?

In the side bar nav, we have Livestock as parent nav to "All livestock, Feeding, Health and Housing" so that's why we have it like that in the structure.

**Pull request closed without merging**
