### PR TITLE
Buttons password

### PR DESCRIPTION
**Pull request by Lil-Adonis**
password reveal, buttons, inputs.

### CODE REVIEW

**Comment by kessysenlong** [comment]
@Lil-Adonis is this a refactor PR? 
If yes, why does it have the feeding schedule changes? Isn't there a separate PR for that?

**Comment by Lil-Adonis** [comment]
> @Lil-Adonis is this a refactor PR? If yes, why does it have the feeding schedule changes? Isn't there a separate PR for that?

the branch that has the updated SetRationForm is AC-82-fe-update-ration-creation-modal so opt it out when merging.
the history existed because i checked out from the branch  (AC-82-fe-update-ration-creation-modal)

**Comment by kessysenlong** [comment]
You need to fix the merge conflicts in this PR @Lil-Adonis

**Comment by Lil-Adonis** [comment]
> You need to fix the merge conflicts in this PR @Lil-Adonis

resolved

**Pull request closed without merging**
